var AppError = require('./AppError');
module.exports = class NotFoundException extends AppError {
    constructor() {
        super('Nenhum conte√∫do encontrado', 404);
    }
}